import "@/lib/styles/globals.css";
import type { Metadata } from "next";
import { Providers } from "@/components/providers";
import { jetbrainsMono, poppins, inter, roboto_mono } from "@/lib/config/fonts";

export const metadata: Metadata = {
  title: "nextPg",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${jetbrainsMono.variable} ${inter.variable} ${roboto_mono.variable} bg-gradient-to-br from-background via-background/80 to-primary/5 transition-colors duration-300 ease-linear`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
