import "@/lib/styles/globals.css";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { Providers } from "@/components/providers";
import { getLocale, getMessages } from "next-intl/server";
import { jetbrainsMono, poppins, inter, roboto_mono } from "@/lib/config/fonts";
import type { ReactNode } from "react";

export const metadata: Metadata = {
  title: "nextPg",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
};

export default async function RootLayout({ children }: Props) {
  
  const messages = await getMessages();
  const locale = await getLocale();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${poppins.variable} ${jetbrainsMono.variable} ${inter.variable} ${roboto_mono.variable} transition-colors duration-100 ease-linear`}
      >
        <NextIntlClientProvider messages={messages}>
          <Providers>{children}</Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

// bg-gradient-to-br from-background via-background/80 to-primary/5
